project:
  type: website
  resources:
    - "wasm/**"
    - "js/**"
    - "posts.html"
    - "editor.html"
    - "users.html"

website:
  title: "WasmPosts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.html
        text: Posts
      - href: editor.html
        text: New Post
      - href: users.html
        text: Users
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
